version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5.4
    steps:
      - checkout

      - run: sudo pip install pipenv

      - run: 
          command: |
            pipenv install --dev
            pipenv run tox
